version: "2"

networks:
    web:
        external: true

services:
    basepg:
        container_name: basepg
        restart: unless-stopped
        image: python:3-alpine
        volumes:
          - ./app:/app
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro
        working_dir: /app        
        command: sh -c "pip install --upgrade pip && pip3 install --root-user-action=ignore requests && pip install psycopg2-binary waitress flask flask_sqlalchemy config && python app.py"
        ports:
          - 5000:5000
        networks:
          - web